{{- if .Values.oidc.enabled }}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: awx
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  # advancedProtocolMappers disabled - requires admin-fine-grained-authz feature in Keycloak
  advancedProtocolMappers: false
  clientId: {{ .Values.oidc.clientId }}
  # Let Keycloak auto-generate the client secret - will be stored in keycloak-client-awx-secret
  realmRef:
    kind: ClusterKeycloakRealm
    name: main
  # Standard OIDC flow for web applications
  directAccess: false
  public: false
  standardFlowEnabled: true
  implicitFlowEnabled: false
  # Redirect URIs
  {{- with .Values.oidc.redirectUris }}
  redirectUris:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  # Web origins for CORS
  {{- with .Values.oidc.webOrigins }}
  webOrigins:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  # Post-logout redirect URIs for proper logout flow (Keycloak 26.x)
  attributes:
    post.logout.redirect.uris: "{{ (first .Values.oidc.redirectUris) }}"
  # Protocol mappers for proper token claims
  protocolMappers:
    - name: audience
      protocol: openid-connect
      protocolMapper: "oidc-audience-mapper"
      config:
        included.client.audience: "{{ .Values.oidc.clientId }}"
        id.token.claim: 'true'
        access.token.claim: 'true'
    - name: groups
      protocol: openid-connect
      protocolMapper: "oidc-group-membership-mapper"
      config:
        claim.name: "groups"
        full.path: 'false'
        id.token.claim: 'true'
        access.token.claim: 'true'
        userinfo.token.claim: 'true'
    - name: username
      protocol: openid-connect
      protocolMapper: "oidc-usermodel-property-mapper"
      config:
        claim.name: "preferred_username"
        user.attribute: "username"
        id.token.claim: 'true'
        access.token.claim: 'true'
        userinfo.token.claim: 'true'
    - name: email
      protocol: openid-connect
      protocolMapper: "oidc-usermodel-property-mapper"
      config:
        claim.name: "email"
        user.attribute: "email"
        id.token.claim: 'true'
        access.token.claim: 'true'
        userinfo.token.claim: 'true'
    - name: first_name
      protocol: openid-connect
      protocolMapper: "oidc-usermodel-property-mapper"
      config:
        claim.name: "given_name"
        user.attribute: "firstName"
        id.token.claim: 'true'
        access.token.claim: 'true'
        userinfo.token.claim: 'true'
    - name: last_name
      protocol: openid-connect
      protocolMapper: "oidc-usermodel-property-mapper"
      config:
        claim.name: "family_name"
        user.attribute: "lastName"
        id.token.claim: 'true'
        access.token.claim: 'true'
        userinfo.token.claim: 'true'
{{- end }}
