# =============================================================================
# AWX KeycloakClient Resource
# =============================================================================
# Creates the OIDC client in Keycloak for AWX SSO integration.
# Uses the EDP Keycloak Operator to manage the client lifecycle.
# =============================================================================
{{- if .Values.oidc.enabled }}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: awx
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  advancedProtocolMappers: true
  clientId: {{ .Values.oidc.clientId }}
  defaultClientScopes:
    - groups
    - edp
  # Reference to the secret that will store the client secret
  secret: $keycloak-client-awx-secret:clientSecret
  # Reference to the ClusterKeycloakRealm (master realm)
  realmRef:
    kind: ClusterKeycloakRealm
    name: main
  # AWX web URL for redirects
  webUrl: https://awx.ops.techsecom.io
  # Additional redirect URIs
  redirectUris:
    {{- range .Values.oidc.redirectUris }}
    - {{ . | quote }}
    {{- end }}
  # Web origins for CORS
  webOrigins:
    {{- range .Values.oidc.webOrigins }}
    - {{ . | quote }}
    {{- end }}
{{- end }}
