{{- if .Values.gitlab.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: sonar-gitlab-alm-setup
  labels:
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: gitlab-setup
        image: curlimages/curl:latest
        env:
        - name: SONAR_URL
          value: "http://sonar.{{ .Release.Namespace }}.svc.cluster.local:9000"
        - name: SONAR_ADMIN_USER
          value: "admin"
        - name: SONAR_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonar-gitlab-secret
              key: adminPassword
        - name: GITLAB_URL
          value: {{ .Values.gitlab.url | quote }}
        - name: GITLAB_CONFIG_NAME
          value: {{ .Values.gitlab.configName | default "gitlab" | quote }}
        - name: GITLAB_PAT
          valueFrom:
            secretKeyRef:
              name: sonar-gitlab-secret
              key: personalAccessToken
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Waiting for SonarQube to be ready..."
          until curl -sf "${SONAR_URL}/api/system/status" | grep -q '"status":"UP"'; do
            echo "SonarQube not ready, waiting..."
            sleep 10
          done
          echo "SonarQube is ready"

          # Use default admin password if secret doesn't exist
          ADMIN_PASS="${SONAR_ADMIN_PASSWORD:-admin}"

          echo "Checking existing GitLab ALM settings..."
          EXISTING=$(curl -sf -u "admin:${ADMIN_PASS}" "${SONAR_URL}/api/alm_settings/list" 2>/dev/null || echo '{"almSettings":[]}')

          if echo "$EXISTING" | grep -q "\"key\":\"${GITLAB_CONFIG_NAME}\""; then
            echo "GitLab configuration '${GITLAB_CONFIG_NAME}' already exists, updating..."
            RESULT=$(curl -s -w "\n%{http_code}" -u "admin:${ADMIN_PASS}" \
              -X POST "${SONAR_URL}/api/alm_settings/update_gitlab" \
              -d "key=${GITLAB_CONFIG_NAME}" \
              -d "newKey=${GITLAB_CONFIG_NAME}" \
              -d "url=${GITLAB_URL}" \
              -d "personalAccessToken=${GITLAB_PAT}")
            HTTP_CODE=$(echo "$RESULT" | tail -1)
            if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "204" ]; then
              echo "GitLab configuration updated successfully"
            else
              echo "Warning: Failed to update GitLab configuration (HTTP $HTTP_CODE)"
              echo "$RESULT" | head -n -1
            fi
          else
            echo "Creating new GitLab configuration '${GITLAB_CONFIG_NAME}'..."
            RESULT=$(curl -s -w "\n%{http_code}" -u "admin:${ADMIN_PASS}" \
              -X POST "${SONAR_URL}/api/alm_settings/create_gitlab" \
              -d "key=${GITLAB_CONFIG_NAME}" \
              -d "url=${GITLAB_URL}" \
              -d "personalAccessToken=${GITLAB_PAT}")
            HTTP_CODE=$(echo "$RESULT" | tail -1)
            if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "204" ]; then
              echo "GitLab configuration created successfully"
            else
              echo "Warning: Failed to create GitLab configuration (HTTP $HTTP_CODE)"
              echo "$RESULT" | head -n -1
            fi
          fi

          echo ""
          echo "GitLab ALM setup complete!"
          echo "Users can now import projects from GitLab at: ${GITLAB_URL}"
{{- end }}
