{{- if .Values.gitlab.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: sonar-gitlab-alm-setup
  labels:
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: gitlab-setup
        image: curlimages/curl:latest
        env:
        - name: SONAR_URL
          value: "http://sonar.{{ .Release.Namespace }}.svc.cluster.local:9000"
        - name: SONAR_ADMIN_USER
          value: "admin"
        - name: SONAR_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonar-gitlab-secret
              key: adminPassword
        - name: GITLAB_URL
          value: {{ .Values.gitlab.url | quote }}
        - name: GITLAB_CONFIG_NAME
          value: {{ .Values.gitlab.configName | default "gitlab" | quote }}
        - name: GITLAB_PAT
          valueFrom:
            secretKeyRef:
              name: sonar-gitlab-secret
              key: personalAccessToken
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Waiting for SonarQube to be ready..."
          until curl -sf "${SONAR_URL}/api/system/status" | grep -q '"status":"UP"'; do
            echo "SonarQube not ready, waiting..."
            sleep 10
          done
          echo "SonarQube is ready"

          ADMIN_PASS="${SONAR_ADMIN_PASSWORD}"

          # Normalize GitLab URL - remove trailing slash
          GITLAB_URL_CLEAN=$(echo "${GITLAB_URL}" | sed 's:/*$::')
          echo "Using GitLab URL: ${GITLAB_URL_CLEAN}"

          # Verify GitLab API is accessible
          echo "Verifying GitLab API access..."
          if curl -sf -H "PRIVATE-TOKEN: ${GITLAB_PAT}" "${GITLAB_URL_CLEAN}/api/v4/user" >/dev/null 2>&1; then
            echo "GitLab API is accessible"
          else
            echo "Warning: Cannot access GitLab API - check token and URL"
          fi

          # Delete existing config to ensure clean state (avoid redirect issues)
          echo "Removing any existing GitLab configuration..."
          curl -sf -u "admin:${ADMIN_PASS}" -X POST "${SONAR_URL}/api/alm_settings/delete" \
            -d "key=${GITLAB_CONFIG_NAME}" 2>/dev/null || true

          # Create fresh GitLab configuration
          echo "Creating GitLab configuration '${GITLAB_CONFIG_NAME}'..."
          RESULT=$(curl -s -w "\n%{http_code}" -u "admin:${ADMIN_PASS}" \
            -X POST "${SONAR_URL}/api/alm_settings/create_gitlab" \
            -d "key=${GITLAB_CONFIG_NAME}" \
            -d "url=${GITLAB_URL_CLEAN}" \
            -d "personalAccessToken=${GITLAB_PAT}")
          HTTP_CODE=$(echo "$RESULT" | tail -1)
          BODY=$(echo "$RESULT" | head -n -1)

          if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "204" ]; then
            echo "GitLab configuration created successfully"
          else
            echo "Warning: Failed to create GitLab configuration (HTTP $HTTP_CODE)"
            echo "$BODY"
          fi

          # Validate the connection
          echo ""
          echo "Validating GitLab connection..."
          VALIDATE=$(curl -s -w "\n%{http_code}" -u "admin:${ADMIN_PASS}" \
            -X POST "${SONAR_URL}/api/alm_settings/validate" \
            -d "key=${GITLAB_CONFIG_NAME}")
          VAL_CODE=$(echo "$VALIDATE" | tail -1)
          VAL_BODY=$(echo "$VALIDATE" | head -n -1)

          if [ "$VAL_CODE" = "200" ] || [ "$VAL_CODE" = "204" ]; then
            echo "GitLab connection validated successfully"
          else
            echo "Warning: GitLab validation returned HTTP $VAL_CODE"
            echo "$VAL_BODY"
          fi

          echo ""
          echo "GitLab ALM setup complete!"
          echo "Users can now import projects from GitLab at: ${GITLAB_URL_CLEAN}"
{{- end }}
