{{- if index .Values "eck-stack" "eck-elasticsearch" "auth" "roles" }}
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-admin
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  roles.yml: |
    # Admin role with full cluster privileges
    admin:
      cluster:
        - all
      indices:
        - names:
            - '*'
          privileges:
            - all
          allow_restricted_indices: false

    # Read-only role for monitoring
    monitoring_viewer:
      cluster:
        - monitor
      indices:
        - names:
            - '*'
          privileges:
            - read
            - view_index_metadata
            - monitor

    # Logs reader role
    logs_reader:
      cluster:
        - monitor
      indices:
        - names:
            - 'container-logs-*'
            - 'audit-logs-*'
            - 'filebeat-*'
            - 'logstash-*'
          privileges:
            - read
            - view_index_metadata

    # Logs writer role (for Logstash/Filebeat)
    logs_writer:
      cluster:
        - monitor
        - manage_index_templates
        - manage_ilm
      indices:
        - names:
            - 'container-logs-*'
            - 'audit-logs-*'
            - 'filebeat-*'
            - 'logstash-*'
          privileges:
            - all

    # ILM management role
    ilm_admin:
      cluster:
        - manage_ilm
        - manage_index_templates
        - monitor
      indices:
        - names:
            - '*'
          privileges:
            - manage
            - view_index_metadata
{{- end }}
