{{- if .Values.eso.enabled }}
---
# Database credentials from Vault (for n8n app to connect)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-db-creds
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: n8n-db-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  refreshInterval: 1h
  data:
    - secretKey: DB_POSTGRESDB_USER
      remoteRef:
        key: n8n-postgres-auth
        property: username
    - secretKey: DB_POSTGRESDB_PASSWORD
      remoteRef:
        key: n8n-postgres-auth
        property: password
---
# Encryption key for n8n credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-encryption-key
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: n8n-encryption-key
    creationPolicy: Owner
    deletionPolicy: Retain
  refreshInterval: 1h
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: {{ .Values.eso.vaultPath }}
        property: encryption_key
{{- end }}
