# ===========================================
# ArgoCD Vault Plugin (AVP) ConfigMap
# ===========================================
# Config Management Plugins for secret injection
# Reference: https://argocd-vault-plugin.readthedocs.io/
#
# Plugins:
# - avp-helm: Helm charts with Vault secrets
# - avp-k8s: Plain YAML manifests with Vault secrets
# - avp-kustomize: Kustomize with Vault secrets
# ===========================================
apiVersion: v1
data:
    avp-helm.yaml: |-
        apiVersion: argoproj.io/v1alpha1
        kind: ConfigManagementPlugin
        metadata:
            name: avp-helm
        spec:
            allowConcurrency: true
            discover:
                find:
                    command:
                      - sh
                      - "-c"
                      - "find . -name 'Chart.yaml' && find . -name 'values.yaml'"
            init:
                command:
                  - sh
                  - "-c"
                  - |
                    # Extract required repos from Chart.yaml and add only those
                    if [ -f Chart.yaml ]; then
                      repos=$(grep -E '^\s*repository:' Chart.yaml | awk '{print $2}' | tr -d '"' | tr -d "'" | sort -u)
                      for repo in $repos; do
                        # Skip file:// and oci:// repos
                        case "$repo" in
                          file://*|oci://*) continue ;;
                        esac
                        # Generate a short name from URL
                        name=$(echo "$repo" | sed 's|https://||;s|http://||;s|/.*||;s|\..*||')
                        helm repo add "$name" "$repo" --force-update --insecure-skip-tls-verify 2>/dev/null || true
                      done
                    fi
                    helm dependency build --skip-refresh 2>/dev/null || helm dependency build 2>/dev/null || true
            generate:
                command:
                  - sh
                  - "-c"
                  - |
                    helm template $ARGOCD_APP_NAME --include-crds -n $ARGOCD_APP_NAMESPACE . |
                    argocd-vault-plugin generate -
            lockRepo: false
    avp-k8s.yaml: |-
        apiVersion: argoproj.io/v1alpha1
        kind: ConfigManagementPlugin
        metadata:
            name: avp-k8s
        spec:
            allowConcurrency: true
            discover:
                find:
                    command:
                      - sh
                      - "-c"
                      - "find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
            generate:
                command:
                  - argocd-vault-plugin
                  - generate
                  - "."
            lockRepo: false
    avp-kustomize.yaml: |-
        apiVersion: argoproj.io/v1alpha1
        kind: ConfigManagementPlugin
        metadata:
            name: avp-kustomize
        spec:
            allowConcurrency: true
            discover:
                find:
                    command:
                      - find
                      - "."
                      - -name
                      - kustomization.yaml
            generate:
                command:
                  - sh
                  - "-c"
                  - "kustomize build . | argocd-vault-plugin generate -"
            lockRepo: false
immutable: false
kind: ConfigMap
metadata:
    name: avp-cmp-plugin
    namespace: argocd
