# =============================================================================
# Botkube Cilium Network Policy
# =============================================================================
# Allows egress traffic for botkube to:
# - Download plugins from GitHub
# - Connect to Slack API
# - Communicate with Prometheus
# - Access Kubernetes API
# =============================================================================
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: botkube-allow-egress
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector: {}
  egress:
    # Allow DNS
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP

    # Allow HTTPS to external services (GitHub, Slack)
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP

    # Allow HTTP (for local plugins server)
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP

    # Allow communication within cluster
    - toEntities:
        - cluster

    # Allow access to Kubernetes API
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP

    # Allow Prometheus metrics collection
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: monitoring
      toPorts:
        - ports:
            - port: "9090"
              protocol: TCP
