cloudnative-pg:
  replicaCount: 1

plugin-barman-cloud:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# replicas: 3

# storage:
#   size: 20Gi
#   storageClass: "vsphere"

# superuserSecret: postgres-superuser-secret

# liveCluster: postgres-v17

# previousCluster: postgres-v17

# roles:
# - name: admin
#   ensure: present
#   comment: "friendly user"
#   login: true
#   superuser: true
#   createdb: true
#   createrole: false
#   inRoles:
#   - pg_monitor
#   - pg_signal_backen
