apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: minio-oidc
    annotations:
        # Sync ExternalSecret before main MinIO deployment
        argocd.argoproj.io/sync-wave: "-2"
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
    refreshInterval: 1m
    secretStoreRef:
        kind: ClusterSecretStore
        name: vault
    target:
        name: minio-oidc
        creationPolicy: Owner
    data:
      - secretKey: clientId
        remoteRef:
            key: minio
            property: client_id
      - secretKey: clientSecret
        remoteRef:
            key: minio
            property: client_secret