# Internal HTTPS access for MinIO S3 API via ingress-nginx
# This enables Harbor S3 redirect by providing HTTPS access internally
# Split-horizon DNS (coredns-custom) rewrites s3.ops.techsecom.io to this service
#
# The existing MinIO ingress already has:
# - TLS certificate (s3-tls-certificate)
# - S3-compatible nginx annotations (proxy settings, header handling)
#
# We create an internal headless service that points to the ingress controller,
# allowing internal DNS resolution to reach the ingress without external routing
---
apiVersion: v1
kind: Service
metadata:
  name: minio-https
  namespace: minio
  labels:
    app: minio-internal-https
  annotations:
    description: "Internal HTTPS endpoint for MinIO S3 API via ingress-nginx"
spec:
  type: ExternalName
  externalName: nginx-ingress-nginx-controller.ingress-nginx.svc.cluster.local
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
