{{- if .Values.eso.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: botkube-teams-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: botkube-teams-secret
    creationPolicy: Owner
  data:
    # Environment variables for Botkube Teams credentials
    # Uses default-group to match Botkube helm chart structure
    - secretKey: BOTKUBE_COMMUNICATIONS_DEFAULT-GROUP_TEAMS_APPID
      remoteRef:
        key: secret/botkube
        property: teamsAppId
    - secretKey: BOTKUBE_COMMUNICATIONS_DEFAULT-GROUP_TEAMS_APPPASSWORD
      remoteRef:
        key: secret/botkube
        property: teamsAppPassword
{{- end }}
