{{- if .Values.oidc.enabled }}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: defectdojo
spec:
  advancedProtocolMappers: true
  clientId: {{ .Values.oidc.clientId }}
  secret: $keycloak-client-defectdojo-secret:clientSecret
  realmRef:
    kind: ClusterKeycloakRealm
    name: main
  # Standard OIDC flow for web applications
  directAccess: false
  public: false
  standardFlowEnabled: true
  implicitFlowEnabled: false
  serviceAccountsEnabled: false
  # Redirect URIs
  {{- with .Values.oidc.redirectUris }}
  redirectUris:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  # Web origins for CORS
  {{- with .Values.oidc.webOrigins }}
  webOrigins:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  # Protocol mappers for proper token claims
  protocolMappers:
    - name: audience
      protocol: openid-connect
      protocolMapper: "oidc-audience-mapper"
      config:
        included.client.audience: "{{ .Values.oidc.clientId }}"
        id.token.claim: 'true'
        access.token.claim: 'true'
    - name: groups
      protocol: openid-connect
      protocolMapper: "oidc-group-membership-mapper"
      config:
        claim.name: "groups"
        full.path: 'false'
        id.token.claim: 'true'
        access.token.claim: 'true'
        userinfo.token.claim: 'true'
    - name: username
      protocol: openid-connect
      protocolMapper: "oidc-usermodel-property-mapper"
      config:
        claim.name: "preferred_username"
        user.attribute: "username"
        id.token.claim: 'true'
        access.token.claim: 'true'
        userinfo.token.claim: 'true'
    - name: email
      protocol: openid-connect
      protocolMapper: "oidc-usermodel-property-mapper"
      config:
        claim.name: "email"
        user.attribute: "email"
        id.token.claim: 'true'
        access.token.claim: 'true'
        userinfo.token.claim: 'true'
    - name: first_name
      protocol: openid-connect
      protocolMapper: "oidc-usermodel-property-mapper"
      config:
        claim.name: "given_name"
        user.attribute: "firstName"
        id.token.claim: 'true'
        access.token.claim: 'true'
        userinfo.token.claim: 'true'
    - name: last_name
      protocol: openid-connect
      protocolMapper: "oidc-usermodel-property-mapper"
      config:
        claim.name: "family_name"
        user.attribute: "lastName"
        id.token.claim: 'true'
        access.token.claim: 'true'
        userinfo.token.claim: 'true'
{{- end }}
