# PostgreSQL credentials from Vault
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reportportal-postgresql-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: reportportal-postgresql-creds
    template:
      engineVersion: v2
      data:
        password: "{{ `{{ .password }}` }}"
  data:
    - secretKey: password
      remoteRef:
        key: /reportportal/
        property: postgresqlPassword
---
# Elasticsearch credentials from Vault
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reportportal-elasticsearch-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: reportportal-elasticsearch-creds
    template:
      engineVersion: v2
      data:
        username: "{{ `{{ .username }}` }}"
        password: "{{ `{{ .password }}` }}"
  data:
    - secretKey: username
      remoteRef:
        key: /reportportal/
        property: elasticsearchUsername
    - secretKey: password
      remoteRef:
        key: /reportportal/
        property: elasticsearchPassword
---
# MinIO credentials from Vault
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reportportal-minio-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: reportportal-minio-creds
    template:
      engineVersion: v2
      data:
        access-key: "{{ `{{ .accessKey }}` }}"
        secret-key: "{{ `{{ .secretKey }}` }}"
  data:
    - secretKey: accessKey
      remoteRef:
        key: /reportportal/
        property: minioAccessKey
    - secretKey: secretKey
      remoteRef:
        key: /reportportal/
        property: minioSecretKey
---
# RabbitMQ credentials from Vault
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reportportal-rabbitmq-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: reportportal-rabbitmq-creds
    template:
      engineVersion: v2
      data:
        password: "{{ `{{ .password }}` }}"
        erlang-cookie: "{{ `{{ .erlangCookie }}` }}"
  data:
    - secretKey: password
      remoteRef:
        key: /reportportal/
        property: rabbitmqPassword
    - secretKey: erlangCookie
      remoteRef:
        key: /reportportal/
        property: rabbitmqErlangCookie
---
# Superadmin credentials from Vault
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reportportal-superadmin-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: reportportal-superadmin-creds
    template:
      engineVersion: v2
      data:
        password: "{{ `{{ .password }}` }}"
  data:
    - secretKey: password
      remoteRef:
        key: /reportportal/
        property: superadminPassword
