apiVersion: v2
name: kubevirt-manager
description: KubeVirt Manager - Web UI for managing KubeVirt Virtual Machines
type: application
version: 1.0.0
appVersion: "1.5.3"
keywords:
  - kubevirt
  - kubevirt-manager
  - virtualization
  - vm
  - virtual-machine
  - web-ui
home: https://kubevirt-manager.io
sources:
  - https://github.com/kubevirt-manager/kubevirt-manager
maintainers:
  - name: Techsecom
