# Critical namespaces backup schedules
# Configuration is managed in values.yaml under 'schedules'
{{- if .Values.schedules.daily.enabled }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: critical-namespaces-daily
  namespace: velero
spec:
  schedule: {{ .Values.schedules.daily.schedule | quote }}
  template:
    includedNamespaces:
      {{- range .Values.schedules.criticalNamespaces }}
      - {{ . }}
      {{- end }}
    includeClusterResources: {{ .Values.schedules.defaults.includeClusterResources }}
    defaultVolumesToFsBackup: {{ .Values.schedules.defaults.defaultVolumesToFsBackup }}
    storageLocation: {{ .Values.schedules.defaults.storageLocation }}
    ttl: {{ .Values.schedules.daily.ttl }}
  useOwnerReferencesInBackup: true
{{- end }}
---
{{- if .Values.schedules.weekly.enabled }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: critical-namespaces-weekly
  namespace: velero
spec:
  schedule: {{ .Values.schedules.weekly.schedule | quote }}
  template:
    includedNamespaces:
      {{- range .Values.schedules.criticalNamespaces }}
      - {{ . }}
      {{- end }}
    includeClusterResources: {{ .Values.schedules.defaults.includeClusterResources }}
    defaultVolumesToFsBackup: {{ .Values.schedules.defaults.defaultVolumesToFsBackup }}
    storageLocation: {{ .Values.schedules.defaults.storageLocation }}
    ttl: {{ .Values.schedules.weekly.ttl }}
  useOwnerReferencesInBackup: true
{{- end }}
---
{{- if .Values.schedules.monthly.enabled }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: critical-namespaces-monthly
  namespace: velero
spec:
  schedule: {{ .Values.schedules.monthly.schedule | quote }}
  template:
    includedNamespaces:
      {{- range .Values.schedules.criticalNamespaces }}
      - {{ . }}
      {{- end }}
    includeClusterResources: {{ .Values.schedules.defaults.includeClusterResources }}
    defaultVolumesToFsBackup: {{ .Values.schedules.defaults.defaultVolumesToFsBackup }}
    storageLocation: {{ .Values.schedules.defaults.storageLocation }}
    ttl: {{ .Values.schedules.monthly.ttl }}
  useOwnerReferencesInBackup: true
{{- end }}
