apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clickhouse-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: clickhouse-auth
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: ""
  data:
  - secretKey: username
    remoteRef:
      key: secret/gitlab/
      property: dbusername
  - secretKey: password
    remoteRef:
      key: secret/gitlab/
      property: dbpassword
