# =============================================================================
# GitLab OIDC Provider ExternalSecret
# =============================================================================
# Syncs OIDC credentials from Vault to create the GitLab OmniAuth provider
# configuration for Keycloak OIDC authentication.
#
# Reference: https://docs.gitlab.com/ee/administration/auth/oidc.html
# =============================================================================
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-oidc-provider
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: gitlab-oidc-provider
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        # GitLab OmniAuth OIDC provider configuration
        # Format: https://docs.gitlab.com/ee/administration/auth/oidc.html
        provider: |
          name: openid_connect
          label: 'Keycloak SSO'
          icon: 'https://www.keycloak.org/resources/images/icon.svg'
          args:
            name: openid_connect
            scope:
              - openid
              - profile
              - email
              - groups
            response_type: code
            issuer: '{{ .issuer }}'
            discovery: true
            client_auth_method: basic
            uid_field: preferred_username
            pkce: true
            client_options:
              identifier: '{{ .clientId }}'
              secret: '{{ .clientSecret }}'
              redirect_uri: 'https://gitlab.ops.techsecom.io/users/auth/openid_connect/callback'
  data:
    - secretKey: clientId
      remoteRef:
        key: gitlab-oidc
        property: oidc-client-id
    - secretKey: clientSecret
      remoteRef:
        key: gitlab-oidc
        property: oidc-client-secret
    - secretKey: issuer
      remoteRef:
        key: gitlab-oidc
        property: oidc-issuer-url
