apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: gitlab-runner-clusterrole
rules:
  - apiGroups: [ "" ]
    resources:
      - namespaces
      - secrets
      - configmaps
      - services
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: [ "apps" ]
    resources:
      - deployments
      - statefulsets
      - daemonsets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: [ "batch" ]
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: [ "" ]
    resources:
      - pods/exec
    verbs:
      - create
  # KubeVirt CDI - DataVolumes and DataSources for ISO images
  - apiGroups: [ "cdi.kubevirt.io" ]
    resources:
      - datavolumes
      - datasources
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  # KubeVirt - VMs for Packer builds
  - apiGroups: [ "kubevirt.io" ]
    resources:
      - virtualmachines
      - virtualmachineinstances
      - virtualmachineexports
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: gitlab-runner-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: gitlab 
roleRef:
    kind: ClusterRole
    name: gitlab-runner-clusterrole
    apiGroup: rbac.authorization.k8s.io
