{{- if .Values.eso.enabled }}
# Admin credentials from Vault
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: keycloak-admin-creds
  data:
    - secretKey: username
      remoteRef:
        key: keycloak
        property: username
    - secretKey: password
      remoteRef:
        key: keycloak
        property: password
---
# Database credentials from Vault
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: keycloak-db-creds
    template:
      engineVersion: v2
      data:
        username: "{{ `{{ .dbUsername }}` }}"
        password: "{{ `{{ .dbPassword }}` }}"
  data:
    - secretKey: dbUsername
      remoteRef:
        key: keycloak
        property: dbUsername
    - secretKey: dbPassword
      remoteRef:
        key: keycloak
        property: dbPassword
---
# OIDC Identity Provider credentials from Vault
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-oidc-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: keycloak-oidc-creds
  data:
    - secretKey: clientId
      remoteRef:
        key: keycloak
        property: oidcClientId
    - secretKey: clientSecret
      remoteRef:
        key: keycloak
        property: oidcClientSecret
    - secretKey: issuer
      remoteRef:
        key: keycloak
        property: oidcIssuer
    - secretKey: wellKnown
      remoteRef:
        key: keycloak
        property: oidcWellKnown
    - secretKey: authEndpoint
      remoteRef:
        key: keycloak
        property: oidcAuthEndpoint
    - secretKey: tokenEndpoint
      remoteRef:
        key: keycloak
        property: oidcTokenEndpoint
    - secretKey: jwksUri
      remoteRef:
        key: keycloak
        property: oidcJwksUri
    - secretKey: userInfoEndpoint
      remoteRef:
        key: keycloak
        property: oidcUserInfoEndpoint
    - secretKey: endSessionEndpoint
      remoteRef:
        key: keycloak
        property: oidcEndSessionEndpoint
    - secretKey: revocationEndpoint
      remoteRef:
        key: keycloak
        property: oidcRevocationEndpoint
{{- end }}
