# BuyCheapNow E-commerce Platform Database
# Provides HA PostgreSQL via CloudNativePG for the BuyCheapNow application
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: buycheapnow-db
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  name: buycheapnow
  owner: buycheapnow
  cluster:
    name: cnpg-cluster
