# =============================================================================
# Harbor PostgreSQL User Secret for CNPG
# =============================================================================
# This ExternalSecret syncs the Harbor database user credentials from Vault.
# CNPG uses this secret to create/manage the 'harbor' PostgreSQL user.
#
# IMPORTANT: Both this secret (for CNPG) and the harbor-user-secret in the
# harbor namespace must read from the same Vault keys (dbUsername/dbPassword)
# to ensure credentials match.
# =============================================================================
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: harbor-user-secret
spec:
    refreshInterval: 1h
    secretStoreRef:
        kind: ClusterSecretStore
        name: vault
    target:
        name: harbor-user-secret
        creationPolicy: Owner
        template:
            metadata:
                labels:
                    cnpg.io/reload: ""
    data:
      - secretKey: username
        remoteRef:
            key: secret/harbor
            property: dbUsername
      - secretKey: password
        remoteRef:
            key: secret/harbor
            property: dbPassword