apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonar-user-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: sonar-user-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: ""
  data:
    - secretKey: username
      remoteRef:
        key: sonar
        property: dbusername
    - secretKey: password
      remoteRef:
        key: sonar
        property: dbpassword
