apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-user-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: vault-user-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: ""
  data:
    - secretKey: username
      remoteRef:
        key: vault-postgres-auth
        property: username
    - secretKey: password
      remoteRef:
        key: vault-postgres-auth
        property: password
