apiVersion: v2
name: report-portal
description: A Helm chart for report-portal

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# The chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 25.12.19

# Version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "25.2.0"

dependencies:
  - name: reportportal
    version: 25.12.19
    repository: https://reportportal.io/kubernetes
  # RabbitMQ is still needed as ReportPortal dependency
  # PostgreSQL, Elasticsearch, and MinIO are external (CNPG, ECK, existing MinIO)
