{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: kubevirt-manager
    app.kubernetes.io/name: kubevirt-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevirt-manager
  labels:
    app: kubevirt-manager
    app.kubernetes.io/name: kubevirt-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  # Core Kubernetes resources
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
      - pods
      - pods/exec
      - services
      - secrets
      - configmaps
      - persistentvolumeclaims
      - persistentvolumes
      - events
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Kubernetes apps resources
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs: ["get", "list", "watch"]
  # Storage resources
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
    verbs: ["get", "list", "watch"]
  # KubeVirt resources
  - apiGroups: ["kubevirt.io"]
    resources:
      - virtualmachines
      - virtualmachineinstances
      - virtualmachineinstancemigrations
      - virtualmachineinstancepresets
      - virtualmachineinstancereplicasets
      - virtualmachinepools
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # KubeVirt subresources
  - apiGroups: ["subresources.kubevirt.io"]
    resources:
      - virtualmachines/start
      - virtualmachines/stop
      - virtualmachines/restart
      - virtualmachines/pause
      - virtualmachines/unpause
      - virtualmachines/migrate
      - virtualmachines/addvolume
      - virtualmachines/removevolume
      - virtualmachines/memorydump
      - virtualmachineinstances/console
      - virtualmachineinstances/vnc
      - virtualmachineinstances/guestosinfo
      - virtualmachineinstances/filesystemlist
      - virtualmachineinstances/userlist
      - virtualmachineinstances/pause
      - virtualmachineinstances/unpause
      - virtualmachineinstances/freeze
      - virtualmachineinstances/unfreeze
      - virtualmachineinstances/softreboot
      - virtualmachineinstances/portforward
      - virtualmachineinstances/sev/fetchcertchain
      - virtualmachineinstances/sev/querylaunchmeasurement
      - virtualmachineinstances/sev/injectlaunchsecret
    verbs: ["get", "update"]
  # KubeVirt instancetypes and preferences
  - apiGroups: ["instancetype.kubevirt.io"]
    resources:
      - virtualmachineinstancetypes
      - virtualmachineclusterinstancetypes
      - virtualmachinepreferences
      - virtualmachineclusterpreferences
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # KubeVirt exports and snapshots
  - apiGroups: ["export.kubevirt.io"]
    resources:
      - virtualmachineexports
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["snapshot.kubevirt.io"]
    resources:
      - virtualmachinesnapshots
      - virtualmachinesnapshotcontents
      - virtualmachinerestores
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # CDI resources
  - apiGroups: ["cdi.kubevirt.io"]
    resources:
      - datavolumes
      - datasources
      - volumeimportsources
      - storageprofiles
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["upload.cdi.kubevirt.io"]
    resources:
      - uploadtokenrequests
    verbs: ["get", "list", "watch", "create"]
  # KubeVirt Manager resources
  - apiGroups: ["kubevirt-manager.io"]
    resources:
      - images
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Cluster API resources (optional)
  - apiGroups: ["cluster.x-k8s.io"]
    resources:
      - clusters
      - machinedeployments
      - machines
      - machinesets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Control plane resources (optional)
  - apiGroups: ["controlplane.cluster.x-k8s.io"]
    resources:
      - kubeadmcontrolplanes
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Infrastructure resources (optional)
  - apiGroups: ["infrastructure.cluster.x-k8s.io"]
    resources:
      - kubevirtclusters
      - kubevirtmachinetemplates
      - kubevirtmachines
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Bootstrap resources (optional)
  - apiGroups: ["bootstrap.cluster.x-k8s.io"]
    resources:
      - kubeadmconfigtemplates
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Scheduling resources
  - apiGroups: ["scheduling.k8s.io"]
    resources:
      - priorityclasses
    verbs: ["get", "list", "watch"]
  # Network resources
  - apiGroups: ["k8s.cni.cncf.io"]
    resources:
      - network-attachment-definitions
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-manager
  labels:
    app: kubevirt-manager
    app.kubernetes.io/name: kubevirt-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt-manager
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
---
# Cloud Controller Manager role for VM networking
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevirt-manager-kccm
  labels:
    app: kubevirt-manager
    app.kubernetes.io/name: kubevirt-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups: ["kubevirt.io"]
    resources:
      - virtualmachines
      - virtualmachineinstances
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - services
      - services/status
      - nodes
      - nodes/status
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources:
      - events
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-manager-kccm
  labels:
    app: kubevirt-manager
    app.kubernetes.io/name: kubevirt-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt-manager-kccm
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
