{{- if .Values.cdi.enabled }}
# CDI (Containerized Data Importer) Operator
# Allows importing VM disk images from various sources
apiVersion: v1
kind: Namespace
metadata:
  name: cdi
  labels:
    app.kubernetes.io/name: cdi
    app.kubernetes.io/component: namespace
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cdi-operator
  namespace: cdi
  labels:
    app.kubernetes.io/name: cdi
    app.kubernetes.io/component: operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cdi-operator
  labels:
    app.kubernetes.io/name: cdi
    app.kubernetes.io/component: operator
rules:
  - apiGroups: ["cdi.kubevirt.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["upload.cdi.kubevirt.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources:
      - pods
      - pods/exec
      - pods/log
      - services
      - endpoints
      - persistentvolumeclaims
      - configmaps
      - secrets
      - serviceaccounts
      - events
      - namespaces
      - nodes
    verbs: ["*"]
  - apiGroups: [""]
    resources:
      - persistentvolumes
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs: ["*"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs: ["*"]
  - apiGroups: ["apiregistration.k8s.io"]
    resources:
      - apiservices
    verbs: ["*"]
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["*"]
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - servicemonitors
      - prometheusrules
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
      - ingresses
    verbs: ["*"]
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
      - csidrivers
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs: ["*"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources:
      - volumesnapshots
      - volumesnapshotclasses
      - volumesnapshotcontents
    verbs: ["*"]
  - apiGroups: ["security.openshift.io"]
    resources:
      - securitycontextconstraints
    verbs: ["*"]
  - apiGroups: ["route.openshift.io"]
    resources:
      - routes
    verbs: ["*"]
  - apiGroups: ["config.openshift.io"]
    resources:
      - proxies
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cdi-operator
  labels:
    app.kubernetes.io/name: cdi
    app.kubernetes.io/component: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cdi-operator
subjects:
  - kind: ServiceAccount
    name: cdi-operator
    namespace: cdi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdi-operator
  namespace: cdi
  labels:
    app.kubernetes.io/name: cdi
    app.kubernetes.io/component: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cdi-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: cdi-operator
        prometheus.cdi.kubevirt.io: "true"
    spec:
      serviceAccountName: cdi-operator
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: cdi-operator
          image: quay.io/kubevirt/cdi-operator:{{ .Values.cdi.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
          env:
            - name: DEPLOY_CLUSTER_RESOURCES
              value: "true"
            - name: OPERATOR_VERSION
              value: {{ .Values.cdi.version }}
            - name: CONTROLLER_IMAGE
              value: quay.io/kubevirt/cdi-controller:{{ .Values.cdi.version }}
            - name: IMPORTER_IMAGE
              value: quay.io/kubevirt/cdi-importer:{{ .Values.cdi.version }}
            - name: CLONER_IMAGE
              value: quay.io/kubevirt/cdi-cloner:{{ .Values.cdi.version }}
            - name: APISERVER_IMAGE
              value: quay.io/kubevirt/cdi-apiserver:{{ .Values.cdi.version }}
            - name: UPLOAD_SERVER_IMAGE
              value: quay.io/kubevirt/cdi-uploadserver:{{ .Values.cdi.version }}
            - name: UPLOAD_PROXY_IMAGE
              value: quay.io/kubevirt/cdi-uploadproxy:{{ .Values.cdi.version }}
            - name: VERBOSITY
              value: "1"
            - name: PULL_POLICY
              value: IfNotPresent
            - name: MONITORING_NAMESPACE
          resources:
            requests:
              cpu: 100m
              memory: 150Mi
            limits:
              cpu: 500m
              memory: 500Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      priorityClassName: system-cluster-critical
{{- end }}
