# KubeVirt Custom Resource - configures the KubeVirt installation
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: kubevirt
    app.kubernetes.io/component: kubevirt
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      {{- if .Values.kubevirt.configuration.developerConfiguration.useEmulation }}
      useEmulation: true
      {{- end }}
      featureGates:
        {{- range .Values.kubevirt.configuration.developerConfiguration.featureGates }}
        - {{ . }}
        {{- end }}
    network:
      defaultNetworkInterface: {{ .Values.kubevirt.configuration.network.defaultNetworkInterface }}
      permitSlirpInterface: {{ .Values.kubevirt.configuration.network.permitSlirpInterface }}
      permitBridgeInterfaceOnPodNetwork: {{ .Values.kubevirt.configuration.network.permitBridgeInterfaceOnPodNetwork }}
    migrations:
      allowAutoConverge: {{ .Values.kubevirt.configuration.migrations.allowAutoConverge }}
      parallelMigrationsPerCluster: {{ .Values.kubevirt.configuration.migrations.parallelMigrationsPerCluster }}
      parallelOutboundMigrationsPerNode: {{ .Values.kubevirt.configuration.migrations.parallelOutboundMigrationsPerNode }}
      bandwidthPerMigration: {{ .Values.kubevirt.configuration.migrations.bandwidthPerMigration | quote }}
      completionTimeoutPerGiB: {{ .Values.kubevirt.configuration.migrations.completionTimeoutPerGiB }}
      progressTimeout: {{ .Values.kubevirt.configuration.migrations.progressTimeout }}
    {{- with .Values.kubevirt.configuration.smbios }}
    smbios:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    # Deploy common-instancetypes (VirtualMachineClusterInstancetypes and VirtualMachineClusterPreferences)
    {{- if .Values.kubevirt.configuration.commonInstancetypesDeployment }}
    commonInstancetypesDeployment:
      enabled: {{ .Values.kubevirt.configuration.commonInstancetypesDeployment.enabled | default true }}
    {{- end }}
  # Customize component resources to meet LimitRange requirements (min CPU 100m)
  # Also add descheduler eviction prevention annotations
  customizeComponents:
    patches:
      # virt-api - CPU requests and descheduler eviction prevention (label + annotation)
      - resourceType: Deployment
        resourceName: virt-api
        patch: '[{"op": "replace", "path": "/spec/template/spec/containers/0/resources/requests/cpu", "value": "100m"}]'
        type: json
      - resourceType: Deployment
        resourceName: virt-api
        patch: '[{"op": "add", "path": "/spec/template/metadata/annotations/descheduler.alpha.kubernetes.io~1evict", "value": "false"}]'
        type: json
      - resourceType: Deployment
        resourceName: virt-api
        patch: '[{"op": "add", "path": "/spec/template/metadata/labels/descheduler.alpha.kubernetes.io~1evict", "value": "false"}]'
        type: json
      # virt-controller - CPU requests and descheduler eviction prevention (label + annotation)
      - resourceType: Deployment
        resourceName: virt-controller
        patch: '[{"op": "replace", "path": "/spec/template/spec/containers/0/resources/requests/cpu", "value": "100m"}]'
        type: json
      - resourceType: Deployment
        resourceName: virt-controller
        patch: '[{"op": "add", "path": "/spec/template/metadata/annotations/descheduler.alpha.kubernetes.io~1evict", "value": "false"}]'
        type: json
      - resourceType: Deployment
        resourceName: virt-controller
        patch: '[{"op": "add", "path": "/spec/template/metadata/labels/descheduler.alpha.kubernetes.io~1evict", "value": "false"}]'
        type: json
      # virt-handler - CPU requests and descheduler eviction prevention (label + annotation)
      - resourceType: DaemonSet
        resourceName: virt-handler
        patch: '[{"op": "replace", "path": "/spec/template/spec/containers/0/resources/requests/cpu", "value": "100m"}]'
        type: json
      - resourceType: DaemonSet
        resourceName: virt-handler
        patch: '[{"op": "add", "path": "/spec/template/metadata/annotations/descheduler.alpha.kubernetes.io~1evict", "value": "false"}]'
        type: json
      - resourceType: DaemonSet
        resourceName: virt-handler
        patch: '[{"op": "add", "path": "/spec/template/metadata/labels/descheduler.alpha.kubernetes.io~1evict", "value": "false"}]'
        type: json
      # virt-handler - Add /dev volume mount for init container QEMU probing (needs /dev/kvm)
      - resourceType: DaemonSet
        resourceName: virt-handler
        patch: '[{"op": "add", "path": "/spec/template/spec/volumes/-", "value": {"name": "host-dev", "hostPath": {"path": "/dev", "type": "Directory"}}}]'
        type: json
      - resourceType: DaemonSet
        resourceName: virt-handler
        patch: '[{"op": "add", "path": "/spec/template/spec/initContainers/0/volumeMounts/-", "value": {"name": "host-dev", "mountPath": "/dev"}}]'
        type: json
      # virt-handler - Add cgroup volume mount for init container (libvirt needs cgroups for QEMU process management)
      - resourceType: DaemonSet
        resourceName: virt-handler
        patch: '[{"op": "add", "path": "/spec/template/spec/volumes/-", "value": {"name": "host-cgroup", "hostPath": {"path": "/sys/fs/cgroup", "type": "Directory"}}}]'
        type: json
      - resourceType: DaemonSet
        resourceName: virt-handler
        patch: '[{"op": "add", "path": "/spec/template/spec/initContainers/0/volumeMounts/-", "value": {"name": "host-cgroup", "mountPath": "/sys/fs/cgroup"}}]'
        type: json
      # virt-handler - Add custom libvirt qemu.conf to run QEMU as root (fixes permission issues in containers)
      - resourceType: DaemonSet
        resourceName: virt-handler
        patch: '[{"op": "add", "path": "/spec/template/spec/volumes/-", "value": {"name": "libvirt-config", "configMap": {"name": "kubevirt-libvirt-config"}}}]'
        type: json
      - resourceType: DaemonSet
        resourceName: virt-handler
        patch: '[{"op": "add", "path": "/spec/template/spec/initContainers/0/volumeMounts/-", "value": {"name": "libvirt-config", "mountPath": "/etc/libvirt/qemu.conf", "subPath": "qemu.conf"}}]'
        type: json
      # virt-exportproxy - CPU requests and descheduler eviction prevention (label + annotation)
      - resourceType: Deployment
        resourceName: virt-exportproxy
        patch: '[{"op": "replace", "path": "/spec/template/spec/containers/0/resources/requests/cpu", "value": "100m"}]'
        type: json
      - resourceType: Deployment
        resourceName: virt-exportproxy
        patch: '[{"op": "add", "path": "/spec/template/metadata/annotations/descheduler.alpha.kubernetes.io~1evict", "value": "false"}]'
        type: json
      - resourceType: Deployment
        resourceName: virt-exportproxy
        patch: '[{"op": "add", "path": "/spec/template/metadata/labels/descheduler.alpha.kubernetes.io~1evict", "value": "false"}]'
        type: json
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy:
    workloadUpdateMethods:
      - LiveMigrate
