# Admin credentials for EDP Keycloak Operator to connect to Keycloak
# This secret is used by ClusterKeycloak resource
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: keycloak-admin-creds
  data:
    - secretKey: username
      remoteRef:
        key: keycloak
        property: username
    - secretKey: password
      remoteRef:
        key: keycloak
        property: password
