{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: atlantis
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: atlantis
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: atlantis
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
