{{- if .Values.adminCliFix.enabled }}
# =============================================================================
# RBAC for Admin CLI Fix Job
# =============================================================================
# Permissions to list/get pods and exec into Keycloak pods
# =============================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-admin-cli-fix
  labels:
    app.kubernetes.io/name: keycloakx
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-admin-cli-fix
  labels:
    app.kubernetes.io/name: keycloakx
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-admin-cli-fix
  labels:
    app.kubernetes.io/name: keycloakx
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keycloak-admin-cli-fix
subjects:
- kind: ServiceAccount
  name: keycloak-admin-cli-fix
  namespace: {{ .Release.Namespace }}
{{- end }}
