# CiliumNetworkPolicy for Keycloak egress
# Keycloak needs outbound HTTPS for:
# - OIDC identity provider federation
# - LDAP/AD connections
# - SMTP for password reset emails
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: keycloak-allow-egress
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector: {}
  ingress:
    - fromEntities:
        - cluster
  egress:
    # Allow DNS resolution via kube-dns
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    # Allow HTTPS/LDAP/SMTP to external IdPs and servers
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "80"
              protocol: TCP
            - port: "389"
              protocol: TCP
            - port: "636"
              protocol: TCP
            - port: "587"
              protocol: TCP
            - port: "465"
              protocol: TCP
    # Allow communication within cluster (Postgres)
    - toEntities:
        - cluster
