{{- if .Values.oidcIdp.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-oidc-idp-setup
  labels:
    app.kubernetes.io/name: keycloakx
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: oidc-setup
        image: curlimages/curl:latest
        env:
        - name: KEYCLOAK_URL
          value: "http://keycloakx-http.{{ .Release.Namespace }}.svc.cluster.local"
        - name: KEYCLOAK_HEALTH_URL
          value: "http://keycloakx-http.{{ .Release.Namespace }}.svc.cluster.local:9000"
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: keycloak-admin-creds
              key: username
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-admin-creds
              key: password
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: keycloak-oidc-creds
              key: clientId
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: keycloak-oidc-creds
              key: clientSecret
        - name: OIDC_ISSUER
          valueFrom:
            secretKeyRef:
              name: keycloak-oidc-creds
              key: issuer
        - name: OIDC_AUTH_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: keycloak-oidc-creds
              key: authEndpoint
        - name: OIDC_TOKEN_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: keycloak-oidc-creds
              key: tokenEndpoint
        - name: OIDC_USERINFO_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: keycloak-oidc-creds
              key: userInfoEndpoint
        - name: OIDC_JWKS_URI
          valueFrom:
            secretKeyRef:
              name: keycloak-oidc-creds
              key: jwksUri
        - name: OIDC_END_SESSION_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: keycloak-oidc-creds
              key: endSessionEndpoint
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Waiting for Keycloak to be ready..."
          until curl -sf "${KEYCLOAK_HEALTH_URL}/health/ready"; do
            echo "Keycloak not ready, waiting..."
            sleep 5
          done
          echo "Keycloak is ready"

          echo "Getting admin token..."
          TOKEN=$(curl -sf -X POST "${KEYCLOAK_URL}/realms/master/protocol/openid-connect/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "username=${ADMIN_USER}" \
            -d "password=${ADMIN_PASSWORD}" \
            -d "grant_type=password" \
            -d "client_id=admin-cli" | sed 's/.*"access_token":"\([^"]*\)".*/\1/')

          if [ -z "$TOKEN" ]; then
            echo "Failed to get admin token"
            exit 1
          fi

          echo "Checking if IDP exists..."
          # Use -s (silent) without -f (fail) to capture HTTP status code even on 404
          IDP_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" \
            "${KEYCLOAK_URL}/admin/realms/master/identity-provider/instances/techsecoms-oidc" \
            -H "Authorization: Bearer ${TOKEN}")

          IDP_CONFIG='{
            "alias": "techsecoms-oidc",
            "displayName": "Techsecoms SSO",
            "providerId": "oidc",
            "enabled": true,
            "trustEmail": true,
            "storeToken": true,
            "addReadTokenRoleOnCreate": false,
            "firstBrokerLoginFlowAlias": "first broker login",
            "config": {
              "clientId": "'"${OIDC_CLIENT_ID}"'",
              "clientSecret": "'"${OIDC_CLIENT_SECRET}"'",
              "issuer": "'"${OIDC_ISSUER}"'",
              "authorizationUrl": "'"${OIDC_AUTH_ENDPOINT}"'",
              "tokenUrl": "'"${OIDC_TOKEN_ENDPOINT}"'",
              "userInfoUrl": "'"${OIDC_USERINFO_ENDPOINT}"'",
              "jwksUrl": "'"${OIDC_JWKS_URI}"'",
              "logoutUrl": "'"${OIDC_END_SESSION_ENDPOINT}"'",
              "validateSignature": "true",
              "useJwksUrl": "true",
              "pkceEnabled": "true",
              "pkceMethod": "S256",
              "syncMode": "IMPORT",
              "clientAuthMethod": "client_secret_basic",
              "defaultScope": "openid profile email"
            }
          }'

          if [ "$IDP_EXISTS" = "200" ]; then
            echo "IDP already exists, updating..."
            curl -sf -X PUT "${KEYCLOAK_URL}/admin/realms/master/identity-provider/instances/techsecoms-oidc" \
              -H "Authorization: Bearer ${TOKEN}" \
              -H "Content-Type: application/json" \
              -d "${IDP_CONFIG}"
            echo "IDP updated successfully"
          else
            echo "Creating new IDP..."
            curl -sf -X POST "${KEYCLOAK_URL}/admin/realms/master/identity-provider/instances" \
              -H "Authorization: Bearer ${TOKEN}" \
              -H "Content-Type: application/json" \
              -d "${IDP_CONFIG}"
            echo "IDP created successfully"
          fi

          # Configure IDP mapper to auto-assign admin role
          echo ""
          echo "Configuring role mapper for admin access..."

          # Get admin role to verify it exists
          echo "Verifying admin role exists..."
          ADMIN_ROLE=$(curl -s "${KEYCLOAK_URL}/admin/realms/master/roles/admin" \
            -H "Authorization: Bearer ${TOKEN}")
          echo "Admin role: $ADMIN_ROLE"

          # Mapper configuration for hardcoded realm role
          # Using hardcoded-role-idp-mapper which assigns a realm role to all users from this IDP
          MAPPER_CONFIG='{
            "name": "admin-role-mapper",
            "identityProviderMapper": "hardcoded-role-idp-mapper",
            "identityProviderAlias": "techsecoms-oidc",
            "config": {
              "syncMode": "INHERIT",
              "role": "admin"
            }
          }'

          # Check if admin-role-mapper exists
          echo "Checking existing mappers..."
          MAPPERS=$(curl -s "${KEYCLOAK_URL}/admin/realms/master/identity-provider/instances/techsecoms-oidc/mappers" \
            -H "Authorization: Bearer ${TOKEN}")
          echo "Existing mappers: $MAPPERS"

          # Extract mapper ID - handle JSON where id may come before or after name
          MAPPER_ID=""
          if echo "$MAPPERS" | grep -q '"name":"admin-role-mapper"'; then
            # Mapper exists, extract the id from the object containing admin-role-mapper
            MAPPER_ID=$(echo "$MAPPERS" | sed 's/},{/}\n{/g' | grep '"name":"admin-role-mapper"' | grep -o '"id":"[^"]*"' | head -1 | sed 's/"id":"//;s/"//')
          fi
          echo "Mapper ID found: $MAPPER_ID"

          if [ -n "$MAPPER_ID" ] && [ "$MAPPER_ID" != "" ]; then
            echo "Role mapper already exists (ID: $MAPPER_ID), skipping update."
            echo "Mapper configuration is already in place."
          else
            echo "Creating role mapper..."
            RESULT=$(curl -s -w "\n%{http_code}" -X POST "${KEYCLOAK_URL}/admin/realms/master/identity-provider/instances/techsecoms-oidc/mappers" \
              -H "Authorization: Bearer ${TOKEN}" \
              -H "Content-Type: application/json" \
              -d "${MAPPER_CONFIG}")
            HTTP_CODE=$(echo "$RESULT" | tail -1)
            BODY=$(echo "$RESULT" | sed '$d')
            if [ "$HTTP_CODE" = "201" ] || [ "$HTTP_CODE" = "200" ]; then
              echo "Role mapper created successfully"
            else
              echo "Failed to create mapper (HTTP $HTTP_CODE): $BODY"
              exit 1
            fi
          fi

          echo ""
          echo "OIDC Identity Provider setup complete with admin role auto-assignment!"
{{- end }}
