---
# =============================================================================
# ExternalSecret for GitHub Runner Token
# =============================================================================
# Pulls the GitHub PAT from Vault for runner authentication
# The token needs 'repo' and 'admin:org' scopes for organization runners
# =============================================================================
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-runner-token
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: github-actions-runner
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: github-runner-token
    template:
      engineVersion: v2
      data:
        # ARC expects the token in this specific key
        github_token: "{{ `{{ .githubToken }}` }}"
  data:
  - secretKey: githubToken
    remoteRef:
      key: secret/github/runner
      property: pat
