apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: clkhouse-gitlab
  namespace: gitlab
spec:
  clusterDef: clickhouse
  topology: cluster
  terminationPolicy: WipeOut
  componentSpecs:
  - name: ch-keeper
    serviceVersion: 25.4.4
    replicas: 1
    disableExporter: false
    services:
    - name: default
      serviceType: ClusterIP
    systemAccounts:
    - name: admin
      passwordConfig:
        length: 10
        numDigits: 5
        numSymbols: 0
        letterCase: MixedCases
        seed: clkhouse-gitlab
    resources:
      requests:
        cpu: 300m
        memory: 1Gi
      # limits:
      #   cpu: 200m
      #   memory: 1Gi
    volumeClaimTemplates:
    - name: data
      spec:
        storageClassName: nfs-csi
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
  shardings:
  - name: clickhouse
    shards: 3
    template:
      name: clickhouse
      serviceVersion: 25.10.3
      env:
      - name: "INIT_CLUSTER_NAME"
        value: "default"
      replicas: 3
      disableExporter: false
      services:
      - name: default
        serviceType: ClusterIP
      systemAccounts:
      - name: admin
        passwordConfig:
          length: 10
          numDigits: 5
          numSymbols: 0
          letterCase: MixedCases
          seed: clkhouse-gitlab
      resources:
        requests:
          cpu: 300m
          memory: 1Gi
        limits:
          cpu: 300m
          memory: 1Gi
      volumeClaimTemplates:
      - name: data
        spec:
          storageClassName: nfs-csi
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
