apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: gitlab-runner
spec:
  targetNamespace: gitlab
  createNamespace: true
  # version: "9.6.1"
  chart: gitlab-runner
  bootstrap: true
  repo: https://charts.gitlab.io/
  valuesContent: |-
    replicas: 3

    gitlabUrl: "https://gitlab.ops.techsecom.io"
    runnerToken: "glrt-u4sm8ez3GByY0YB-CKTPUm86MQp0OjEKdToxCw.01.120y9k00b"
    # certsSecretName: gitlab-wildcard-tls-chain

    metrics:
      enabled: true
      portName: metrics
      port: 9252
      serviceMonitor:
        enabled: true

    envVars:
      - name: DOCKER_TLS_CERTDIR
        value: /certs
      - name: RUNNER_EXECUTOR
        value: kubernetes
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            key: accessKeyId
            name: aws-credentials
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            key: secretAccessKey
            name: aws-credentials
      - name: NO_PROXY
        value: "localhost,127.0.0.1,::1,gitlab.ops.techsecom.io,.svc,.cluster.local"

    extraEnv:
      CACHE_S3_SERVER_ADDRESS: "minio.minio.svc.cluster.local:9000"
      CACHE_S3_BUCKET_NAME: "gitlab-runner-cache"
      CACHE_S3_BUCKET_LOCATION: us-east-1
      CACHE_SHARED: "true"

    extraEnvFrom:
      CACHE_S3_ACCESS_KEY:
        secretKeyRef:
          name: aws-credentials-glab-runner
          key: accesskey
      CACHE_S3_SECRET_KEY:
        secretKeyRef:
          name: aws-credentials-glab-runner
          key: secretkey

    unregisterRunners: true

    rbac:
      create: true

    serviceAccount:
      create: true

    service:
      enabled: true

    resources:
      requests:
        memory: 1000Mi
        cpu: 812m
        ephemeral-storage: 800Mi

    runners:
      cache:
        secretName: aws-credentials-glab-runner

      config: |
        [[runners]]
          name = "k8s-docker-runner"
          request_concurrency = 4
          [runners.kubernetes]
            privileged = true
            poll_timeout = 2000
            node_selector_overwrite_allowed = ".*"
            namespace = "{{ default .Release.Namespace .Values.runners.jobNamespace }}"
            image = "docker:27.3-cli"
            service_account = "default"

          [runners.cache]
            Type = "s3"
            Path = "gitlab-runner"
            Shared = true

          [runners.cache.s3]
            ServerAddress = "minio.minio.svc.cluster.local:9000"
            BucketName = "gitlab-runner-cache"
            BucketLocation = "us-east-1"
            S3ForcePathStyle = true
            Insecure = true

          [[runners.kubernetes.services]]
            name = "docker:27.3-dind"
            privileged = true
            command = ["dockerd-entrypoint.sh"]
            args = ["--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock"]

        # [[runners.kubernetes.volumes.empty_dir]]
        #   name = "docker-certs"
        #   mount_path = "/certs/client"

      privileged: true
      serviceAccountName: gitlab-runner
