apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: redis
spec:
  targetNamespace: gitlab
  createNamespace: true
  # version: "9.6.1"
  chart: redis
  bootstrap: true
  repo: https://charts.bitnami.com/bitnami
  valuesContent: |-
    fullnameOverride: redis
    image:
      registry: docker.io
      repository: bitnamilegacy/redis
    global:
      storageClass: longhorn
    auth:
      enabled: true
      existingSecret: redis-creds
      existingSecretPasswordKey: REDIS_PASSWORD
      sentinel: false
    # commonConfiguration: |-
    #   maxmemory-policy volatile-lru
    #   appendonly yes
    #   save 900 1
    #   save 300 10
    #   save 60 10000

    architecture: replication
    replica:
      replicaCount: 3
      disableCommands:
      - FLUSHDB
      persistence:
        enabled: true
        storageClass: longhorn
        size: 60Gi
      terminationGracePeriodSeconds: 60
      startupProbe:
        enabled: true
        initialDelaySeconds: 60
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 30
      readinessProbe:
        enabled: true
        initialDelaySeconds: 60
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 10
      livenessProbe:
        enabled: true
        initialDelaySeconds: 90
        periodSeconds: 15
        timeoutSeconds: 15
        successThreshold: 1
        failureThreshold: 10

    kubectl:
      image:
        registry: docker.io
        repository: bitnamilegacy/kubectl

    sentinel:
      enabled: true
      image:
        registry: docker.io
        repository: bitnamilegacy/redis-sentinel
      masterSet: mymaster
      quorum: 2
      replicas: 3
      terminationGracePeriodSeconds: 60
      persistence:
        enabled: true
        storageClass: longhorn
        size: 60Gi
      startupProbe:
        enabled: true
        initialDelaySeconds: 60
        periodSeconds: 15
        timeoutSeconds: 15
        failureThreshold: 20
      readinessProbe:
        enabled: true
        initialDelaySeconds: 60
        periodSeconds: 10
        timeoutSeconds: 10
        failureThreshold: 10
      livenessProbe:
        enabled: true
        initialDelaySeconds: 90
        periodSeconds: 15
        timeoutSeconds: 10
        failureThreshold: 10

    volumePermissions:
      enabled: true
      image:
        registry: docker.io
        repository: bitnamilegacy/os-shell

    metrics:
      enabled: true
      image:
        registry: docker.io
        repository: bitnamilegacy/redis-exporter
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus
      startupProbe:
        enabled: true
        initialDelaySeconds: 60
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 10
      livenessProbe:
        enabled: true
        initialDelaySeconds: 90
        periodSeconds: 10
        timeoutSeconds: 10
        successThreshold: 1
        failureThreshold: 5
      readinessProbe:
        enabled: true
        initialDelaySeconds: 60
        periodSeconds: 5
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 3
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: gitlab-redis-cache
spec:
  targetNamespace: gitlab
  createNamespace: true
  # version: "9.6.1"
  chart: redis
  bootstrap: true
  repo: https://charts.bitnami.com/bitnami
  valuesContent: |-
    fullnameOverride: redis-cache
    image:
      registry: docker.io
      repository: bitnamilegacy/redis
    global:
      storageClass: longhorn
    auth:
      enabled: true
      existingSecret: redis-creds
      existingSecretPasswordKey: REDIS_PASSWORD
      sentinel: false
    # commonConfiguration: |-
    #   maxmemory-policy volatile-lru
    #   appendonly yes
    #   save 900 1
    #   save 300 10
    #   save 60 10000

    architecture: replication
    replica:
      replicaCount: 3
      disableCommands:
      - FLUSHDB
      persistence:
        enabled: true
        storageClass: longhorn
        size: 60Gi
      terminationGracePeriodSeconds: 60
      startupProbe:
        enabled: true
        initialDelaySeconds: 60
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 30
      readinessProbe:
        enabled: true
        initialDelaySeconds: 60
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 10
      livenessProbe:
        enabled: true
        initialDelaySeconds: 90
        periodSeconds: 15
        timeoutSeconds: 15
        successThreshold: 1
        failureThreshold: 10

    kubectl:
      image:
        registry: docker.io
        repository: bitnamilegacy/kubectl

    sentinel:
      enabled: true
      image:
        registry: docker.io
        repository: bitnamilegacy/redis-sentinel
      masterSet: mymaster
      quorum: 2
      replicas: 3
      terminationGracePeriodSeconds: 60
      persistence:
        enabled: true
        storageClass: longhorn
        size: 60Gi
      startupProbe:
        enabled: true
        initialDelaySeconds: 60
        periodSeconds: 15
        timeoutSeconds: 15
        failureThreshold: 20
      readinessProbe:
        enabled: true
        initialDelaySeconds: 60
        periodSeconds: 10
        timeoutSeconds: 10
        failureThreshold: 10
      livenessProbe:
        enabled: true
        initialDelaySeconds: 90
        periodSeconds: 15
        timeoutSeconds: 10
        failureThreshold: 10

    volumePermissions:
      enabled: true
      image:
        registry: docker.io
        repository: bitnamilegacy/os-shell

    metrics:
      enabled: true
      image:
        registry: docker.io
        repository: bitnamilegacy/redis-exporter
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus
      startupProbe:
        enabled: true
        initialDelaySeconds: 60
        periodSeconds: 20
        timeoutSeconds: 20
        successThreshold: 1
        failureThreshold: 10
      livenessProbe:
        enabled: true
        initialDelaySeconds: 90
        periodSeconds: 10
        timeoutSeconds: 10
        successThreshold: 1
        failureThreshold: 5
      readinessProbe:
        enabled: true
        initialDelaySeconds: 60
        periodSeconds: 5
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 3
