apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: gitlab-runner
spec:
  targetNamespace: gitlab
  createNamespace: true
  # version: "9.6.1"
  chart: gitlab-runner
  bootstrap: true
  repo: https://charts.gitlab.io/
  valuesContent: |-
    replicas: 3

    revisionHistoryLimit: 50
    certsSecretName: gitlab-wildcard-tls-chain
    gitlabUrl: "https://gitlab.ops.techsecom.io"
    envVars:
    - name: DOCKER_TLS_CERTDIR
      value: /certs
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          key: accessKeyId
          name: aws-credentials
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: secretAccessKey
          name: aws-credentials
    - name: NO_PROXY
      value: "localhost,127.0.0.1,::1,gitlab.ops.techsecom.io,.svc,.cluster.local"
    runnerToken: "glrt-oyBMZNYu_cnxfuWgYlVtdG86MQp0OjEKdToxCw.01.120xdlplk"

    unregisterRunners: true

    logLevel: debug

    logFormat: runner

    rbac:
      create: true

    serviceAccount:
      create: true

    metrics:
      enabled: true

    service:
      enabled: true
    resources: 
      # limits:
      #   memory: 256Mi
      #   cpu: 200m
      #   ephemeral-storage: 512Mi
      requests:
        memory: 1000Mi
        cpu: 812m
        ephemeral-storage: 800Mi
    runners:
      cache: 
        secretName: aws-credentials-glab-runner
      helpers:
        image: "registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:v18.6.1"

      config: |
        [[runners]]
          name = "gitlab-runner"
          # environment = ["FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY=true"]
          [runners.kubernetes]
            privileged = true
            poll_timeout = 2000

            node_selector_overwrite_allowed = ".*"
            namespace = "{{ default .Release.Namespace .Values.runners.jobNamespace }}"
            image = "ubuntu:24.04"
            service_account = "default"

          [runners.cache]
            Type = "s3"
            Path = "gitlab-runner"
            Shared = true
            [runners.cache.s3]
              ServerAddress = "minio.minio.svc.cluster.local:9000"
              BucketName = "gitlab-runner-cache"
              BucketLocation = "us-east-1"
              S3ForcePathStyle = true
              Insecure = true

        [[runners.kubernetes.volumes.empty_dir]]
          name = "docker-certs"
          mount_path = "/certs/client"
          medium = "Memory"

      privileged: true
      serviceAccountName: gitlab-runner
