apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: redis-admin-secret
spec:
    refreshInterval: 1h
    secretStoreRef:
        kind: ClusterSecretStore
        name: vault
    data:
      - secretKey: username
        remoteRef:
            conversionStrategy: Default
            decodingStrategy: None
            key: secret/redis
            metadataPolicy: None
            property: redis-username
      - secretKey: password
        remoteRef:
            conversionStrategy: Default
            decodingStrategy: None
            key: secret/redis
            metadataPolicy: None
            property: redis-password