apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-agent-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: gitlab-agent-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: secret/gitlab-agent/
        property: token
