apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: redis-creds
  data:
    # REDIS_PASSWORD is used by both Bitnami Redis chart and Harbor
    - secretKey: REDIS_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/redis
        metadataPolicy: None
        property: redis-password
