# =============================================================================
# Harbor PostgreSQL Database Secret
# =============================================================================
# This ExternalSecret syncs the Harbor database credentials from Vault.
# The credentials are used by Harbor to connect to the CNPG PostgreSQL cluster.
#
# IMPORTANT: The 'harbor' database user must exist in CNPG with CREATE DATABASE
# permissions, or the database must be pre-created via CNPG Cluster spec.
# =============================================================================
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: harbor-user-secret
spec:
    refreshInterval: 1h
    secretStoreRef:
        kind: ClusterSecretStore
        name: vault
    target:
        name: harbor-user-secret
        creationPolicy: Owner
        template:
            metadata:
                labels:
                    cnpg.io/reload: ""
    data:
      - secretKey: username
        remoteRef:
            key: secret/harbor
            property: dbUsername
      - secretKey: password
        remoteRef:
            key: secret/harbor
            property: dbPassword