# =============================================================================
# Harbor OIDC ExternalSecret
# =============================================================================
# Syncs OIDC client credentials from Vault (seeded by Terraform Keycloak module).
# The Terraform seed uses underscore-separated property names.
# =============================================================================
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: oidc-harbor
    creationPolicy: Owner
  data:
    # Client credentials (seeded by Terraform)
    - secretKey: oidc-client-id
      remoteRef:
        key: harbor
        property: oidc_client_id
    - secretKey: oidc-client-secret
      remoteRef:
        key: harbor
        property: oidc_client_secret
    # Harbor values.yaml references this key as "oidc_issuer-url" (mixed format)
    - secretKey: oidc_issuer-url
      remoteRef:
        key: harbor
        property: oidc_issuer_url

