apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
    name: redis-replication
    namespace: harbor
spec:
    terminationPolicy: Delete
    clusterDef: redis
    topology: replication

    componentSpecs:
      - name: redis
        # Valid options are: [7.0.6,7.2.4]
        serviceVersion: "8.2.1"
        disableExporter: false
        replicas: 2
        systemAccounts:
        - name: default
          secretRef:
            name: redis-admin-secret
            namespace: harbor
        resources:
            limits:
                cpu: '0.5'
                memory: 0.5Gi
            requests:
                cpu: '0.5'
                memory: 0.5Gi
        volumeClaimTemplates:
          - name: data
            spec:
                storageClassName: nfs-csi
                accessModes:
                  - ReadWriteOnce
                resources:
                    requests:
                        storage: 20Gi
      - name: redis-sentinel
        replicas: 3
        systemAccounts:
        - name: default
          secretRef:
            name: redis-admin-secret
            namespace: harbor
        resources:
            limits:
                cpu: '0.5'
                memory: 0.5Gi
            requests:
                cpu: '0.5'
                memory: 0.5Gi
        volumeClaimTemplates:
          - name: data
            spec:
                storageClassName: nfs-csi
                accessModes:
                  - ReadWriteOnce
                resources:
                    requests:
                        storage: 20Gi