apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-apps
  annotations:
    # ApplicationSet sync-wave: Infrastructure deploys first (wave -3)
    argocd.argoproj.io/sync-wave: "-3"
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
  - list:
      elements:
      # =============================================
      # WAVE -3: Core Infrastructure (must be ready before everything)
      # =============================================
      - name: cert-manager
        namespace: cert-manager
        serverSideApply: true
        wave: "-3"  # Deploy first - TLS certificates for all apps
        imageList: "cert-manager=quay.io/jetstack/cert-manager-controller"

      - name: ingress-nginx
        namespace: ingress-nginx
        serverSideApply: true
        wave: "-3"  # Deploy first - ingress for all apps
        imageList: "ingress-nginx=registry.k8s.io/ingress-nginx/controller"
        helm:
          values:
          - values.yaml

      # =============================================
      # DISABLED APPLICATIONS
      # =============================================
      # - name: argocd
      #   namespace: argocd
      #   serverSideApply: true
      #   wave: "-3"

      # - name: kube-cleanup-operator
      #   serverSideApply: true
      #   namespace: kube-cleanup
      #   wave: "0"

  template:
    metadata:
      name: "{{ .name }}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "."
        argocd.argoproj.io/sync-wave: '{{ default "0" (dig "wave" "" .) }}'
        # ArgoCD Image Updater - set imageList in element to enable
        argocd-image-updater.argoproj.io/image-list: '{{ dig "imageList" "" . }}'
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/git-branch: main
        # notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1001726711150"
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/donydonald1/gitops-argocd.git
        targetRevision: HEAD
        path: "infrastructure/{{ .name }}"
      destination:
        name: in-cluster
        namespace: '{{ default .name (dig "namespace" "" .) }}'
      ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
      - group: apps
        kind: "*"
        jqPathExpressions:
        - .spec.template.spec.hostUsers
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        - PruneLast=true
        - PrunePropagationPolicy=foreground
        - SkipDryRunOnMissingResource=true
        - '{{ printf "%s=%s" "ServerSideApply" (dig "serverSideApply" "true" . | toString) }}'
