apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main-apps
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
  - list:
      elements:
      - name: gethomepage
        namespace: homepage
      # - name: focalboard
      #   namespace: focalboard
      # - name: actual
      #   namespace: actual
      # - name: frigate
      #   namespace: frigate
      #   serverSideApply: true
      #   helm:
      #     values:
      #     - "values.yaml"
      # # - name: ghost
      # - name: go-healthcheck
      # - name: prometheus-operator
      #   namespace: monitoring
      #   serverSideApply: true
      # - name: eck-stack
      #   namespace: elastic-system
      #   serverSideApply: true

  template:
    metadata:
      name: "{{ .name }}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "."
        # ArgoCD Image Updater - set imageList in element to enable
        argocd-image-updater.argoproj.io/image-list: '{{ dig "imageList" "" . }}'
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/git-branch: main
        # notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1001726711150"
    spec:
      project: main
      source:
        repoURL: https://github.com/donydonald1/gitops-argocd.git
        targetRevision: HEAD
        path: "main/{{ .name }}"
        # plugin:
        #   name: avp-directory-include
        # env:
        #   - name: FILE_NAME
        #     value: "system/{{ .name }}"
      destination:
        name: in-cluster
        namespace: '{{ default .name (dig "namespace" "" .) }}'
      ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
      - group: apps
        kind: "*"
        jqPathExpressions:
        - .spec.template.spec.hostUsers
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        # - ServerSideApply=true
        - RespectIgnoreDifferences=true
        - PruneLast=true
        - PrunePropagationPolicy=foreground
        - SkipDryRunOnMissingResource=true
        # - RespectIgnoreDifferences=false
        - '{{ printf "%s=%s" "ServerSideApply" (dig "serverSideApply" "true" . | toString) }}'
