apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-apps
  annotations:
    # ApplicationSet sync-wave: Monitoring apps deploy after platform apps (wave 0)
    argocd.argoproj.io/sync-wave: "0"
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
  - list:
      elements:
      # =============================================
      # WAVE 0: Core Monitoring (Prometheus, Grafana, AlertManager)
      # =============================================
      - name: kube-prometheus-stack
        namespace: monitoring
        serverSideApply: true
        SkipCRDs: false
        wave: "0"  # Deploy first - provides CRDs for ServiceMonitors
        helm:
          valueFiles:
          - "values.yaml"

      # =============================================
      # WAVE 1: Logging Stack (requires ECK operator from system wave -2)
      # =============================================
      - name: eck-stack
        namespace: elastic-system
        serverSideApply: true
        wave: "1"  # Deploy after ECK operator is ready
        imageList: "elasticsearch=docker.elastic.co/elasticsearch/elasticsearch, kibana=docker.elastic.co/kibana/kibana, logstash=docker.elastic.co/logstash/logstash"

      # =============================================
      # DISABLED APPLICATIONS
      # =============================================
      # - name: uptime-kuma
      #   namespace: kube-system
      #   wave: "1"
      #   helm:
      #     valueFiles:
      #     - "values.yaml"
      #   serverSideApply: true

      # - name: prometheus-rules
      #   namespace: monitoring
      #   wave: "1"  # After kube-prometheus-stack
      #   serverSideApply: true

      # - name: thanos
      #   namespace: monitoring
      #   wave: "1"  # After Prometheus
      #   serverSideApply: true
      #   helm:
      #     valueFiles:
      #     - "values.yaml"

      # - name: grafana
      #   namespace: monitoring
      #   wave: "1"
      #   serverSideApply: true
      #   helm:
      #     valueFiles:
      #     - "values.yaml"

      # - name: loki
      #   namespace: monitoring
      #   wave: "1"  # After storage (MinIO)
      #   serverSideApply: true
      #   helm:
      #     valueFiles:
      #     - "values.yaml"

      # - name: influxdb
      #   namespace: monitoring
      #   wave: "1"
      #   serverSideApply: true

      # Botkube is managed as a standalone Application with AVP plugin
      # See: monitoring/botkube/application.yaml
      # - name: botkube
      #   namespace: botkube
      #   wave: "2"
      #   serverSideApply: true
      #   helm:
      #     valueFiles:
      #     - "values.yaml"

      # - name: karma
      #   namespace: monitoring
      #   wave: "1"
      #   serverSideApply: true

      # OLD Rancher monitoring-stack - DISABLED
      # - name: monitoring-stack
      #   namespace: cattle-monitoring-system
      #   serverSideApply: true
      #   SkipCRDs: false
      #   imageList: "prometheus=rancher/mirrored-prometheus-prometheus, alertmanager=rancher/mirrored-prometheus-alertmanager, grafana=rancher/mirrored-grafana-grafana"
      #   helm:
      #     valueFiles:
      #     - "values.yaml"

  template:
    metadata:
      name: "{{ .name }}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "."
        argocd.argoproj.io/sync-wave: '{{ default "0" (dig "wave" "" .) }}'
        # ArgoCD Image Updater - set imageList in element to enable
        argocd-image-updater.argoproj.io/image-list: '{{ dig "imageList" "" . }}'
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/git-branch: main
        # notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1001726711150"
    spec:
      project: monitoring
      source:
        repoURL: https://github.com/donydonald1/gitops-argocd.git
        targetRevision: HEAD
        path: "monitoring/{{ .name }}"
        helm:
          valueFiles:
          - values.yaml
      destination:
        name: in-cluster
        namespace: '{{ default .name (dig "namespace" "" .) }}'
      ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
      - group: apps
        kind: "*"
        jqPathExpressions:
        - .spec.template.spec.hostUsers
      # ECK managed resources - ignore operator-managed fields and defaults
      - group: elasticsearch.k8s.elastic.co
        kind: Elasticsearch
        managedFieldsManagers:
        - elastic-operator
        jqPathExpressions:
        - .metadata.annotations
        - .status
        - .spec.http.service
        - .spec.monitoring
        - .spec.nodeSets[].podTemplate.metadata
        - .spec.nodeSets[].volumeClaimTemplates[].status
      - group: kibana.k8s.elastic.co
        kind: Kibana
        managedFieldsManagers:
        - elastic-operator
        jqPathExpressions:
        - .metadata.annotations
        - .status
        - .spec.http.service
        - .spec.monitoring
        - .spec.podTemplate.metadata
        - .spec.enterpriseSearchRef
      - group: logstash.k8s.elastic.co
        kind: Logstash
        managedFieldsManagers:
        - elastic-operator
        jqPathExpressions:
        - .metadata.annotations
        - .status
        - .spec.monitoring
        - .spec.podTemplate.metadata
      - group: beat.k8s.elastic.co
        kind: Beat
        managedFieldsManagers:
        - elastic-operator
        jqPathExpressions:
        - .metadata.annotations
        - .status
        - .spec.monitoring
        - .spec.deployment.podTemplate.metadata
        - .spec.daemonSet.podTemplate.metadata
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
        managedNamespaceMetadata:
          labels:
            goldilocks.fairwinds.com/enabled: "true"
            pod-security.kubernetes.io/enforce: privileged
            pod-security.kubernetes.io/enforce-version: latest
            pod-security.kubernetes.io/audit: privileged
            pod-security.kubernetes.io/audit-version: latest
            pod-security.kubernetes.io/warn: privileged
            pod-security.kubernetes.io/warn-version: latest
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        - PruneLast=true
        - PrunePropagationPolicy=foreground
        - SkipDryRunOnMissingResource=true
        - '{{ printf "%s=%s" "ServerSideApply" (dig "serverSideApply" "true" . | toString) }}'
        # ServerSideDiff helps with operator-managed resources like ECK
        - ServerSideDiff=true
