apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-apps
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
  - list:
      elements:
      # - name: uptime-kuma
      #   namespace: kube-system
      #   helm:
      #     valueFiles:
      #     - "values.yaml"
      #   serverSideApply: true
      # - name: cloudnative-pg
      #   namespace: cnpg-system
      #   serverSideApply: true
      # # - name: ghost
      # - name: go-healthcheck
      # - name: kube-prometheus-stack
      #   namespace: monitoring
      #   serverSideApply: true
      #   helm:
      #     valueFiles:
      #     - "values.yaml"

      # OLD Rancher monitoring-stack - DISABLED
      # - name: monitoring-stack
      #   namespace: cattle-monitoring-system
      #   serverSideApply: true
      #   SkipCRDs: false
      #   imageList: "prometheus=rancher/mirrored-prometheus-prometheus, alertmanager=rancher/mirrored-prometheus-alertmanager, grafana=rancher/mirrored-grafana-grafana"
      #   helm:
      #     valueFiles:
      #     - "values.yaml"

      # NEW Community kube-prometheus-stack
      - name: kube-prometheus-stack
        namespace: monitoring
        serverSideApply: true
        SkipCRDs: false
        helm:
          valueFiles:
          - "values.yaml"
      # - name: prometheus-rules
      #   namespace: monitoring
      #   serverSideApply: tru
      # - name: thanos
      #   namespace: monitoring
      #   serverSideApply: true
      #   helm:
      #     valueFiles:
      #     - "values.yaml"

      # - name: grafana
      #   namespace: monitoring
      #   serverSideApply: true
      #   helm:
      #     valueFiles:
      #     - "values.yaml"
      # - name: loki
      #   namespace: monitoring
      #   serverSideApply: true
      # helm:
      # - name: influxdb
      #   namespace: monitoring
      #   serverSideApply: true

      # - name: botkube
      #   namespace: monitoring
      #   serverSideApply: true

      # - name: karma
      #   namespace: monitoring
      #   serverSideApply: true
      # - name: eck-stack
      #   namespace: elastic-system
      #   helm:
      #     valueFiles:
      #     - "values.yaml"
      #   serverSideApply: true
      # - name: loki
      #   namespace: monitoring
      #   serverSideApply: true
      # helm:
      #   valueFiles:
      #   - "values.yaml"
      # - "manifest-dev.yaml"
      - name: eck-stack
        namespace: elastic-system
        serverSideApply: true
        imageList: "elasticsearch=docker.elastic.co/elasticsearch/elasticsearch, kibana=docker.elastic.co/kibana/kibana, logstash=docker.elastic.co/logstash/logstash"

  template:
    metadata:
      name: "{{ .name }}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "."
        # ArgoCD Image Updater - set imageList in element to enable
        argocd-image-updater.argoproj.io/image-list: '{{ dig "imageList" "" . }}'
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/git-branch: main
        # notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1001726711150"
    spec:
      project: monitoring
      source:
        repoURL: https://github.com/donydonald1/gitops-argocd.git
        targetRevision: HEAD
        path: "monitoring/{{ .name }}"
        # plugin:
        #   name: avp-directory-include
        # env:
        #   - name: FILE_NAME
        #     value: "system/{{ .name }}"
      destination:
        name: in-cluster
        namespace: '{{ default .name (dig "namespace" "" .) }}'
      ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
      - group: apps
        kind: "*"
        jqPathExpressions:
        - .spec.template.spec.hostUsers
      # ECK managed resources - ignore operator-managed fields and defaults
      - group: elasticsearch.k8s.elastic.co
        kind: Elasticsearch
        managedFieldsManagers:
        - elastic-operator
        jqPathExpressions:
        - .metadata.annotations
        - .status
        - .spec.http.service
        - .spec.monitoring
        - .spec.nodeSets[].podTemplate.metadata
        - .spec.nodeSets[].volumeClaimTemplates[].status
      - group: kibana.k8s.elastic.co
        kind: Kibana
        managedFieldsManagers:
        - elastic-operator
        jqPathExpressions:
        - .metadata.annotations
        - .status
        - .spec.http.service
        - .spec.monitoring
        - .spec.podTemplate.metadata
        - .spec.enterpriseSearchRef
      - group: logstash.k8s.elastic.co
        kind: Logstash
        managedFieldsManagers:
        - elastic-operator
        jqPathExpressions:
        - .metadata.annotations
        - .status
        - .spec.monitoring
        - .spec.podTemplate.metadata
      - group: beat.k8s.elastic.co
        kind: Beat
        managedFieldsManagers:
        - elastic-operator
        jqPathExpressions:
        - .metadata.annotations
        - .status
        - .spec.monitoring
        - .spec.deployment.podTemplate.metadata
        - .spec.daemonSet.podTemplate.metadata
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        - PruneLast=true
        - PrunePropagationPolicy=foreground
        - SkipDryRunOnMissingResource=true
        - '{{ printf "%s=%s" "ServerSideApply" (dig "serverSideApply" "true" . | toString) }}'
        # ServerSideDiff helps with operator-managed resources like ECK
        - ServerSideDiff=true
