apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-apps
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
  - list:
      elements:
      # - name: keycloak
      #   namespace: security

      - name: harbor-ha
        namespace: harbor
        serverSideApply: true
        SkipCRDs: true
        wave: "3"  # Deploy after databases and storage are ready
        helm:
          values:
          - values.yaml
      # - name: kubevirt
      #   namespace: kubevirt
      #   serverSideApply: true
      #   SkipCRDs: true
      #   helm:
      #     values:
      #     - values.yaml
      # - name: velero
      #   namespace: velero
      #   serverSideApply: true
      # - name: sonar
      #   namespace: sonar
      - name: gitlab
        wave: "3"  # Deploy after databases (CNPG) and storage (MinIO) are ready
        namespace: gitlab
        serverSideApply: true
        helm:
          values:
          - values.yaml

      - name: minio
        namespace: minio
        serverSideApply: true
        wave: "0"  # Deploy MinIO first (storage for other apps)
        helm:
          values:
          - values.yaml

      - name: cnpg-cluster
        namespace: cnpg-system
        wave: "1"  # Deploy after CNPG operator (wave -1 in system-apps)
        helm:
          values:
          - values.yaml
        serverSideApply: true

      - name: wikijs
        namespace: wikijs
        serverSideApply: true
        wave: "2"  # Deploy after databases are ready

      # # - name: go-healthcheck

      - name: it-tools
        namespace: it-tools
        serverSideApply: true
        wave: "2"
        helm:
          values:
          - values.yaml

      - name: kroki
        namespace: kroki
        serverSideApply: true
        wave: "2"
        helm:
          values:
          - values.yaml

  template:
    metadata:
      name: "{{ .name }}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "."
        argocd.argoproj.io/sync-wave: '{{ default "0" (dig "wave" "" .) }}'
        # notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1001726711150"
        # argocd.argoproj.io/compare-options: '{{ printf "%s=%s" "ServerSideDiff" (dig "serverSideDiff" "false" . | toString) }}'
    spec:
      project: platform
      source:
        repoURL: https://github.com/donydonald1/gitops-argocd.git
        targetRevision: HEAD
        path: "platform/{{ .name }}"
        # plugin:
        #   name: lovely-plugin
      destination:
        name: in-cluster
        namespace: '{{ default .name (dig "namespace" "" .) }}'
      ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
      - group: apps
        kind: "*"
        jqPathExpressions:
        - .spec.template.spec.hostUsers
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        # - ServerSideApply=true
        - SkipCRDs=true
        - RespectIgnoreDifferences=true
        - PruneLast=true
        - PrunePropagationPolicy=foreground
        - SkipDryRunOnMissingResource=true
        # - RespectIgnoreDifferences=false
        - '{{ printf "%s=%s" "ServerSideApply" (dig "serverSideApply" "true" . | toString) }}'
