apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-apps
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
  - list:
      elements:
      - name: argo-cd-image-updater
        namespace: argocd
        serverSideApply: true
        imageList: "image-updater=quay.io/argoprojlabs/argocd-image-updater"

      - name: pod-cleaner
        namespace: pod-cleaner
        serverSideApply: true
        imageList: "pod-cleaner=bolferdocker/nvidia-watcher"

      # - name: k8s-cleaner
      #   namespace: k8s-cleaner
      #   helm:
      #     values:
      #     - values.yaml

      - name: eck-operator
        namespace: elastic-system
        serverSideApply: true
        imageList: "eck-operator=docker.elastic.co/eck/eck-operator"

        # - name: gitlab-operator
        #   namespace: gitlab
        #   serverSideApply: true
        helm:
          values:
          - values.yaml
      # - name: longhorn
      #   namespace: longhorn-system
      #   serverSideApply: true
      #   helm:
      #     values:
      #     - values.yaml

      # - name: awx-operator
      #   namespace: awx-operator
      #   serverSideApply: true

      # - name: change-detection
      #   namespace: change-detection
      #   # #- name: awx-operator

      - name: kured
        namespace: kured
        serverSideApply: true
        imageList: "kured=ghcr.io/kubereboot/kured"

      # - name: external-dns
      #   namespace: external-dns

      # - name: spegel
      #   namespace: spegel

      # - name: jaeger-operator

      - name: keycloak-operator
        namespace: keycloak-operator
        serverSideApply: true
        imageList: "keycloak-operator=epamedp/keycloak-operator"

      # - name: minio-operator
      #   namespace: minio-operator
      #   serverSideApply: true

      # - name: opentelemetry-operator

      # - name: redis-operator
      #   serverSideApply: true

      - name: sonar-operator
        namespace: sonarqube
        serverSideApply: true
        imageList: "sonar-operator=epamedp/sonar-operator"

      - name: keda
        namespace: keda
        serverSideApply: true
        imageList: "keda=ghcr.io/kedacore/keda, keda-metrics=ghcr.io/kedacore/keda-metrics-apiserver"
        helm:
          values:
          - "values.yaml"

      - name: reloader
        namespace: reloader
        serverSideApply: true
        imageList: "reloader=stakater/reloader"

      # - name: descheduler
      #   namespace: descheduler
      #   serverSideApply: true

      - name: node-feature-discovery
        namespace: node-feature-discovery
        serverSideApply: true
        imageList: "nfd=registry.k8s.io/nfd/node-feature-discovery"

      - name: node-problem-detector
        namespace: node-problem-detector
        serverSideApply: true
        imageList: "npd=registry.k8s.io/node-problem-detector/node-problem-detector"
        # - name: external-secrets
        #   namespace: external-secrets
        #   serverSideApply: true
        # - name: couchdb
        # - name: kanboard
        #   namespace: kenboard
        #   serverSideApply: true

      - name: cloudnative-pg
        namespace: cnpg-system
        serverSideApply: true
        wave: "-1"  # Deploy operator before clusters
        imageList: "cnpg=ghcr.io/cloudnative-pg/cloudnative-pg"
        # - name: ghost
        # - name: go-healthcheck

  template:
    metadata:
      name: "{{ .name }}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "."
        notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1001726711150"
        argocd.argoproj.io/sync-wave: '{{ default "0" (dig "wave" "" .) }}'
        # ArgoCD Image Updater - set imageList in element to enable
        argocd-image-updater.argoproj.io/image-list: '{{ dig "imageList" "" . }}'
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/git-branch: main
    spec:
      project: system
      source:
        repoURL: https://github.com/donydonald1/gitops-argocd.git
        targetRevision: HEAD
        path: "system/{{ .name }}"
        # plugin:
        #   name: avp-directory-include
        # env:
        #   - name: FILE_NAME
        #     value: "system/{{ .name }}"
      destination:
        name: in-cluster
        namespace: '{{ default .name (dig "namespace" "" .) }}'
      ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
      - group: apps
        kind: "*"
        jqPathExpressions:
        - .spec.template.spec.hostUsers
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        # - ServerSideApply=true
        - RespectIgnoreDifferences=true
        - PruneLast=true
        - PrunePropagationPolicy=foreground
        - SkipDryRunOnMissingResource=true
        # - RespectIgnoreDifferences=false
        - '{{ printf "%s=%s" "ServerSideApply" (dig "serverSideApply" "true" . | toString) }}'
