{{- if .Values.eso.enabled }}
# DefectDojo PostgreSQL credentials from Vault
# This secret is used by DefectDojo to connect to CNPG cluster
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: defectdojo-postgresql-specific
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: defectdojo-postgresql-specific
  data:
    - secretKey: postgresql-password
      remoteRef:
        key: defectdojo
        property: dbPassword
{{- end }}
