# CiliumNetworkPolicy for SonarQube egress
# SonarQube needs outbound HTTPS for:
# - Plugin marketplace downloads
# - License activation
# - GitLab/GitHub webhooks (outbound)
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: sonar-allow-egress
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector: {}
  ingress:
    - fromEntities:
        - cluster
  egress:
    # Allow DNS resolution via kube-dns
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    # Allow HTTPS to SonarSource servers, plugin marketplace
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "80"
              protocol: TCP
    # Allow communication within cluster (Postgres)
    - toEntities:
        - cluster
