{{- if and .Values.oidc.enabled .Values.eso.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-client-awx-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: keycloak-client-awx-secret
    creationPolicy: Owner
  data:
    - secretKey: clientSecret
      remoteRef:
        key: awx
        property: oidcClientSecret
{{- end }}
